services:
  template:
    build:
      context: .
      dockerfile: apps/template/Dockerfile
    container_name: template
    ports:
      - '4173:3000'
    profiles: ['template_prod']

  template_db:
    image: postgres:18.1
    container_name: template_db
    env_file:
      - ./apps/template/.env
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    volumes:
      - template_pg_data:/var/lib/postgresql
    profiles: ['template_dev', 'template_prod']

  nest_web:
    build:
      context: .
      dockerfile: apps/nest/Dockerfile
    env_file: ./apps/nest/.env
    environment:
      - POSTGRES_HOST=db
    ports:
      - "3000:3000"
    profiles: ['nest_prod']

  nest_db:
    image: postgres:18.1
    container_name: nest_db
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    env_file:
      - ./apps/nest/.env
    volumes:
      - nest_pg_data:/var/lib/postgresql
    profiles: ['nest_dev', 'nest_prod']

volumes:
  template_pg_data:
  nest_pg_data:
