name: Build docker image (release)

on:
  release:
    types:
      - published

jobs:
  check-affected:
    runs-on: ubuntu-latest
    outputs:
      app: ${{ steps.extract-app.outputs.app }}
      version: ${{ steps.extract-app.outputs.version }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Required for proper git history

      - name: Determine app to build
        id: extract-app
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          VERSION=${TAG_NAME#*-}
          APP_NAME=${TAG_NAME%%-*}
          if [[ ! -d "apps/$APP_NAME" ]]; then
            echo "No matching app found for tag: $TAG_NAME"
            exit 1
          fi
          echo "app=$APP_NAME" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  build-app:
    runs-on: ubuntu-latest
    needs: check-affected
    if: ${{ needs.check-affected.outputs.app != '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Debug app
        run: |
          echo "App to build: ${{ needs.check-affected.outputs.app }}"
          echo "Version: ${{ needs.check-affected.outputs.version }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/${{ needs.check-affected.outputs.app }}/Dockerfile
          push: true
          build-args: |
            TARGET=${{ needs.check-affected.outputs.app }}
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/monorepo-apps-${{ needs.check-affected.outputs.app }}:latest
            ${{ vars.DOCKERHUB_USERNAME }}/monorepo-apps-${{ needs.check-affected.outputs.app }}:${{ github.ref_name }}
