name: On release

permissions:
  contents: write

on:
  release:
    types:
      - published

jobs:
  check-affected:
    name: Check affected app or package by the release tag
    runs-on: ubuntu-latest
    outputs:
      target: ${{ steps.extract-app.outputs.target }}
      type: ${{ steps.extract-app.outputs.type }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Determine targeted package or app
        id: extract-app
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          if [[ $TAG_NAME =~ ([0-9]+\.[0-9]+\.[0-9]+([\-\+][A-Za-z0-9.\-+]+)?)$ ]]; then
            VERSION="${BASH_REMATCH[1]}"
            TARGET="${TAG_NAME%-${VERSION}}"
          else
            TARGET=${TAG_NAME%%-*}
          fi
          if [ -d "apps/$TARGET" ]; then
            TYPE=app
          elif [ -d "packages/$TARGET" ]; then
            TYPE=package
          else
            echo "No matching app or package found for tag: $TAG_NAME"
            exit 1
          fi
          echo "target=$TARGET" >> $GITHUB_OUTPUT
          echo "type=$TYPE" >> $GITHUB_OUTPUT

  build-app:
    name: Build and push Docker image for the app
    runs-on: ubuntu-latest
    needs: check-affected
    if: ${{ needs.check-affected.outputs.type == 'app' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Debug app version
        run: |
          echo "App to build: ${{ needs.check-affected.outputs.target }}"
          echo "Version: ${{ github.ref_name }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/${{ needs.check-affected.outputs.target }}/Dockerfile
          push: true
          build-args: |
            TARGET=${{ needs.check-affected.outputs.target }}
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/monorepo-apps-${{ needs.check-affected.outputs.target }}:latest
            ${{ vars.DOCKERHUB_USERNAME }}/monorepo-apps-${{ needs.check-affected.outputs.target }}:${{ github.ref_name }}
